// Polling daemon: every POLL_INTERVAL_MS, pick the oldest open `ready-for-agent`
// issue, transition labels, run the agent, push the branch, open a draft PR.
// Usage: npx tsx .sandcastle/daemon.mts

import { execFileSync } from "node:child_process";
import {
  Issue,
  branchForIssue,
  pickOldestIssueWithLabel,
  runIssue,
} from "./main.mts";

const POLL_INTERVAL_MS = 60_000;

const TRIGGER_LABEL = "ready-for-agent";
const WORKING_LABEL = "agent-working";
const PR_OPEN_LABEL = "agent-pr-open";
const FAILED_LABEL = "agent-failed";

// All labels the agent's state machine owns; we strip these before applying a
// new state so transitions are clean even if a prior run left orphans.
const AGENT_STATE_LABELS = [
  TRIGGER_LABEL,
  WORKING_LABEL,
  PR_OPEN_LABEL,
  FAILED_LABEL,
];

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

function gh(args: string[]): string {
  return execFileSync("gh", args, { encoding: "utf8" });
}

function transitionLabel(issueNumber: number, nextLabel: string) {
  const removeArgs = AGENT_STATE_LABELS.filter((l) => l !== nextLabel).flatMap(
    (l) => ["--remove-label", l],
  );
  gh([
    "issue",
    "edit",
    String(issueNumber),
    "--add-label",
    nextLabel,
    ...removeArgs,
  ]);
}

function commentOnIssue(issueNumber: number, body: string) {
  gh(["issue", "comment", String(issueNumber), "--body", body]);
}

function pushBranch(branch: string) {
  execFileSync("git", ["push", "-u", "origin", branch], { stdio: "inherit" });
}

function existingPrForBranch(branch: string): string | null {
  try {
    const out = gh([
      "pr",
      "list",
      "--head",
      branch,
      "--state",
      "open",
      "--json",
      "url",
      "--limit",
      "1",
    ]);
    const rows = JSON.parse(out) as { url: string }[];
    return rows[0]?.url ?? null;
  } catch {
    return null;
  }
}

function openDraftPr(issue: Issue, branch: string, logFilePath?: string): string {
  const body = [
    `Closes #${issue.number}`,
    ``,
    `Generated by the Sandcastle daemon.`,
    logFilePath ? `\nLog: \`${logFilePath}\`` : "",
  ].join("\n");

  const out = gh([
    "pr",
    "create",
    "--base",
    "main",
    "--head",
    branch,
    "--title",
    issue.title,
    "--body",
    body,
    "--draft",
  ]);
  return out.trim();
}

async function processIssue(issue: Issue): Promise<void> {
  const branch = branchForIssue(issue);

  transitionLabel(issue.number, WORKING_LABEL);

  let result;
  try {
    result = await runIssue(issue);
  } catch (err) {
    console.error(`Run failed for #${issue.number}:`, err);
    transitionLabel(issue.number, FAILED_LABEL);
    commentOnIssue(
      issue.number,
      `Sandcastle run errored. Relabel as \`${TRIGGER_LABEL}\` to retry.`,
    );
    return;
  }

  if (result.commits.length === 0) {
    console.warn(`No commits produced for #${issue.number}.`);
    transitionLabel(issue.number, FAILED_LABEL);
    commentOnIssue(
      issue.number,
      [
        `Sandcastle produced no commits.`,
        `Completion signal: \`${result.completionSignal ?? "(none)"}\`.`,
        result.logFilePath ? `Log: \`${result.logFilePath}\`.` : "",
        `Relabel as \`${TRIGGER_LABEL}\` to retry.`,
      ]
        .filter(Boolean)
        .join(" "),
    );
    return;
  }

  try {
    pushBranch(branch);
  } catch (err) {
    console.error(`Push failed for ${branch}:`, err);
    transitionLabel(issue.number, FAILED_LABEL);
    commentOnIssue(
      issue.number,
      `Sandcastle could not push branch \`${branch}\`. Check daemon logs.`,
    );
    return;
  }

  const existing = existingPrForBranch(branch);
  const prUrl = existing ?? openDraftPr(issue, branch, result.logFilePath);
  transitionLabel(issue.number, PR_OPEN_LABEL);
  console.log(`✓ #${issue.number} → ${prUrl}`);
}

async function tick(): Promise<void> {
  const issue = pickOldestIssueWithLabel(TRIGGER_LABEL);
  if (!issue) return;
  console.log(`Picked up issue #${issue.number}: ${issue.title}`);
  await processIssue(issue);
}

async function main() {
  console.log(
    `Sandcastle daemon started. Polling for \`${TRIGGER_LABEL}\` every ${POLL_INTERVAL_MS / 1000}s.`,
  );
  while (true) {
    try {
      await tick();
    } catch (err) {
      console.error("Tick error (continuing):", err);
    }
    await sleep(POLL_INTERVAL_MS);
  }
}

main();
